# Generated by Django 3.0.3 on 2020-03-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitude')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500, verbose_name='ImageUrl')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('title', models.CharField(max_length=300, verbose_name='Notice Title')),
                ('description', models.TextField(verbose_name='Notice Description')),
                ('lostType', models.CharField(choices=[('Human', 'Animal')], default='Animal', max_length=6, verbose_name='Type')),
                ('award', models.CharField(max_length=100, verbose_name='Award')),
                ('isFind', models.BooleanField()),
                ('finderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='FinderUser', to='account.Account')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Location')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnerUser', to='account.Account')),
            ],
        ),
    ]
