# Generated by Django 3.0.3 on 2020-03-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='finderId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='FinderUser', to='account.Account', verbose_name='Finder User'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='lostType',
            field=models.CharField(choices=[('Human', 'Human'), ('Animal', 'Animal')], default='Animal', max_length=6, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnerUser', to='account.Account', verbose_name='Owner User'),
        ),
    ]
