# Generated by Django 3.0.3 on 2020-03-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20200303_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalType', models.CharField(max_length=100, verbose_name='Animal Type')),
                ('race', models.CharField(max_length=50, verbose_name='Animal race')),
                ('color', models.CharField(max_length=20, verbose_name='Animal color')),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('age', models.CharField(max_length=10, verbose_name='Age')),
                ('clothes', models.TextField(verbose_name='Clothes')),
            ],
        ),
    ]
